version: "3"
services:
  fast-api:
    container_name: fast-api
    build: ./fast-api
    volumes:
      - .:/fast-api-app
    networks:
      - app_network
    ports:
      - "8000:8000"
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 567234
      DATABASE_HOST: postgres_db
      DATABASE_NAME: hw02
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  fast_api_data:

networks:
  app_network:
    driver: bridge